name = "talkthetaste"
compatibility_date = "2026-08-07"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "TTT_DATA"
id = "86a29cb479ca48b9b3e0eea3083f4404"
preview_id = "07d9ef6e85c14b69b8d3c97fcff358fa"
